# Generated by Django 3.2.7 on 2022-03-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resumeout',
            options={'ordering': ['-date'], 'verbose_name': 'Резюме вывод', 'verbose_name_plural': 'Резюме вывод'},
        ),
        migrations.AlterField(
            model_name='resumeout',
            name='date',
            field=models.DateField(verbose_name='Дата размещения'),
        ),
    ]
