# Generated by Django 3.2.7 on 2022-03-03 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='Имя')),
                ('Lastname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('Middle_name', models.CharField(max_length=100, verbose_name='Отчество')),
                ('School', models.IntegerField(verbose_name='Школа')),
                ('Class', models.IntegerField(verbose_name='Класс')),
                ('published', models.DateField(null=True, verbose_name='Дата записи')),
            ],
            options={
                'verbose_name': 'Импорт',
                'verbose_name_plural': 'Импорт',
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='Desktop',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='import.device')),
            ],
            bases=('import.device',),
        ),
    ]
